namespace Radar.Placas.Listener.Domain.Enums
{
    public enum StatusCode : int
    {
        NAOINCIALIZADO = 0,

        //SUCESSO
        SUCESSO = 1000,
        INFORMATIVO = 1100,
        AVISO = 1200,

        //ERRO
        ERRO_GERAL = 2000,

        RECURSO_EXTERNO_ERRO_GERAL = 2000,

        RECURSO_EXTERNO_ERRO_WEBSERVICE = 2200,
        RECURSO_EXTERNO_ERRO_WEBSERVICE_INACESSIVEL = 2210,
        RECURSO_EXTERNO_ERRO_WEBSERVICE_PERMISSAONEGADA = 2220,
        RECURSO_EXTERNO_ERRO_WEBSERVICE_TIMEOUT = 2223,

        RECURSO_EXTERNO_ERRO_BDADOS = 2300,
        RECURSO_EXTERNO_ERRO_BDADOS_INACESSIVEL = 2310,
        RECURSO_EXTERNO_ERRO_BDADOS_PERMISSAONEGADA = 2320,
        RECURSO_EXTERNO_ERRO_BDADOS_TOKEN_FIREBASE_NAO_ENCONTRADO = 2330,

        RECURSO_EXTERNO_ERRO_ARQUIVO = 2400,
        RECURSO_EXTERNO_ERRO_ARQUIVO_INACESSIVEL = 2410,
        RECURSO_EXTERNO_ERRO_ARQUIVO_PERMISSAONEGADA = 2420,

        RECURSO_EXTERNO_ERRO_FILA = 2500,
        RECURSO_EXTERNO_ERRO_FILA_INACESSIVEL = 2510,
        RECURSO_EXTERNO_ERRO_FILA_PERMISSAONEGADA = 2520,

        ERRO_REGRA_NEGOCIO = 2600,
        ERRO_INICIALIZACAO = 2700
    }
}